name: RPC Health Check

on:
  schedule:
    # - cron: '0 0 * * *'  # Runs daily
    - cron: '* * * * *'  # TEST: run every min
  workflow_dispatch:  # Allows manual trigger


jobs:
  check-rpc-health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
